#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "tonemapping.h"
#include "cpp_glsl_compat.h"


layout(local_size_x = 1) in;

layout(binding = 0, set = 0) writeonly buffer minmax_t
{
  HistogramLuminanceRange range;
};

void main(void)
{
  if (gl_GlobalInvocationID.x == 0)
  {
    range.min = SHADER_UINT_MAX;
    range.max = 0;
  }
}

