#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "draw.h"
#include "lights.h"
#include "geometry.h"
#include "constants.h"

layout(local_size_x = BASE_WORK_GROUP_SIZE) in;

layout(binding = 0, set = 0) writeonly buffer light_mats_t
{
  LightMatrices mats;
};

layout(binding = 1, set = 0) uniform light_data_t
{
  UniformLights lights;
};

layout(binding = 8, set = 0) uniform constants_t
{
  Constants constants;
};

layout(binding = 9, set = 0) uniform view_params_t
{
  ViewParams viewParams;
};

const uint POINT_MAT_CNT = POINT_LIGHT_BUF_SIZE * 6;
const uint SPOT_MAT_CNT = SPOT_LIGHT_BUF_SIZE;
const uint DIR_MAT_CNT = DIRECTIONAL_LIGHT_BUF_SIZE * CSM_CASCADE_COUNT;

const vec3 POINT_FACE_DIRS[] = {
  vec3(1.f, 0.f, 0.f),
  vec3(-1.f, 0.f, 0.f),
  vec3(0.f, 1.f, 0.f),
  vec3(0.f, -1.f, 0.f),
  vec3(0.f, 0.f, -1.f),
  vec3(0.f, 0.f, 1.f)};
const vec3 POINT_FACE_UPS[] = {
  vec3(0.f, 1.f, 0.f),
  vec3(0.f, 1.f, 0.f),
  vec3(0.f, 0.f, 1.f),
  vec3(0.f, 0.f, -1.f),
  vec3(0.f, 1.f, 0.f),
  vec3(0.f, 1.f, 0.f)};

void main(void)
{
  const uint idx = gl_GlobalInvocationID.x;
  if (idx < POINT_MAT_CNT)
  {
    const uint iidx = idx;
    const uint lidx = iidx / 6;
    const uint fidx = iidx - lidx * 6;

    const vec3 pos = lights.pointLights[lidx].position;
    const vec3 front = POINT_FACE_DIRS[fidx];
    const vec3 upReal = POINT_FACE_UPS[fidx];
    const vec3 right = normalize(cross(front, upReal));
    const vec3 up = normalize(cross(right, front));
    const mat4 inverseView = mat4(
      vec4(right, 0.f),
      vec4(up, 0.f),
      vec4(front, 0.f),
      vec4(pos, 1.f));
    const mat4 view = inverse(inverseView);
    const float znear = 0.001f;
    const float zfar = lights.pointLights[lidx].range + 0.001f;
    const float invext = -1.f;
    const float invZRng = 1.f / (zfar - znear);
    const mat4 proj = mat4(
      vec4(invext, 0.f, 0.f, 0.f),
      vec4(0.f, invext, 0.f, 0.f),
      vec4(0.f, 0.f, zfar * invZRng, 1.f),
      vec4(0.f, 0.f, -znear * zfar * invZRng, 0.f));

    mats.pointLightMats[lidx][fidx] = proj * view;
  }
  else if (idx < POINT_MAT_CNT + SPOT_MAT_CNT)
  {
    const uint iidx = idx - POINT_MAT_CNT;
    
    const vec3 pos = lights.spotLights[iidx].position;
    const vec3 front = normalize(lights.spotLights[iidx].direction);
    const vec3 upReal =
      max(abs(front.x), abs(front.z)) < SHADER_EPSILON ?
      vec3(0.f, 0.f, 1.f) : vec3(0.f, 1.f, 0.f);
    const vec3 right = normalize(cross(front, upReal));
    const vec3 up = normalize(cross(right, front));
    const mat4 inverseView = mat4(
      vec4(right, 0.f),
      vec4(up, 0.f),
      vec4(front, 0.f),
      vec4(pos, 1.f));
    const mat4 view = inverse(inverseView);
    const float znear = 0.001f;
    const float zfar = lights.spotLights[iidx].range + 0.001f;
    const float invext = 1.f / tan(-lights.spotLights[iidx].outerConeAngle * 0.5f);
    const float invZRng = 1.f / (zfar - znear);
    const mat4 proj = mat4(
      vec4(invext, 0.f, 0.f, 0.f),
      vec4(0.f, invext, 0.f, 0.f),
      vec4(0.f, 0.f, zfar * invZRng, 1.f),
      vec4(0.f, 0.f, -znear * zfar * invZRng, 0.f));

    mats.spotLightMats[iidx] = proj * view;
  }
  else
  {
    const uint iidx = idx - POINT_MAT_CNT - SPOT_MAT_CNT;
    const uint lidx = iidx / CSM_CASCADE_COUNT;
    const uint cidx = iidx - lidx * CSM_CASCADE_COUNT;

    const float minX = lights.directionalLights[lidx].shadowmapCascades[cidx].minX;
    const float maxX = lights.directionalLights[lidx].shadowmapCascades[cidx].maxX;
    const float minY = lights.directionalLights[lidx].shadowmapCascades[cidx].minY;
    const float maxY = lights.directionalLights[lidx].shadowmapCascades[cidx].maxY;
    const float minZ = lights.directionalLights[lidx].shadowmapCascades[cidx].minZ;
    const float maxZ = lights.directionalLights[lidx].shadowmapCascades[cidx].maxZ;

    const float xExt = (maxX - minX) * 0.5f;
    const float yExt = (maxY - minY) * 0.5f;
    const float xCenter = (maxX + minX) * 0.5f;
    const float yCenter = (maxY + minY) * 0.5f;

    const vec3 front = normalize(lights.directionalLights[lidx].direction);
    const vec3 upReal =
      max(abs(front.x), abs(front.z)) < SHADER_EPSILON ?
      vec3(0.f, 0.f, 1.f) : vec3(0.f, 1.f, 0.f);
    const vec3 right = normalize(cross(upReal, front));
    const vec3 up = normalize(cross(front, right));

    const float znear = minZ - CSM_CORRIDOR_SIZE - 0.001f;
    const float zfar = maxZ + 0.001f;

    const vec3 pos = right * xCenter + up * yCenter;

    const mat4 inverseView = mat4(
      vec4(right, 0.f),
      vec4(up, 0.f),
      vec4(front, 0.f),
      vec4(pos, 1.f));
    const mat4 view = inverse(inverseView);

    const mat4 proj = mat4(
      vec4(-1.f / xExt, 0.f, 0.f, 0.f),
      vec4(0.f, -1.f / yExt, 0.f, 0.f),
      vec4(0.f, 0.f, 1.f / (zfar - znear), 0.f),
      vec4(0.f, 0.f, -znear / (zfar - znear), 1.f));

    mats.directionalLightMats[lidx][cidx] = proj * view;
    //mats.directionalLightMats[lidx][cidx] = view; // @TODO: this is not exact with position
  }
}
