#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "draw.h"
#include "lights.h"
#include "geometry.h"
#include "constants.h"

layout(local_size_x = BASE_WORK_GROUP_SIZE) in;

layout(binding = 0, set = 0) writeonly buffer light_mats_t
{
  LightMatrices mats;
};

layout(binding = 1, set = 0) uniform light_data_t
{
  UniformLights lights;
};

layout(binding = 8, set = 0) uniform constants_t
{
  Constants constants;
};

layout(binding = 9, set = 0) uniform view_params_t
{
  ViewParams viewParams;
};

const uint POINT_MAT_CNT = POINT_LIGHT_BUF_SIZE * 6;
const uint SPOT_MAT_CNT = SPOT_LIGHT_BUF_SIZE;
const uint DIR_MAT_CNT = DIRECTIONAL_LIGHT_BUF_SIZE * CSM_CASCADE_COUNT;

void main(void)
{
  const uint idx = gl_GlobalInvocationID.x;
  if (idx < POINT_MAT_CNT)
  {
    const uint iidx = idx;
    const uint lidx = iidx / 6;
    const uint fidx = iidx - lidx;
    // @TODO: remove? We don't need this for cube sampling
  }
  else if (idx < POINT_MAT_CNT + SPOT_MAT_CNT)
  {
    const uint iidx = idx - POINT_MAT_CNT;
    
    const vec3 pos = lights.spotLights[iidx].position;
    const vec3 front = normalize(lights.spotLights[iidx].direction);
    const vec3 upReal =
      max(abs(front.x), abs(front.z)) < SHADER_EPSILON ?
      vec3(0.f, 0.f, 1.f) : vec3(0.f, 1.f, 0.f);
    const vec3 right = normalize(cross(front, upReal));
    const vec3 up = normalize(cross(right, front));
    const mat4 inverseView = mat4(
      vec4(right, 0.f),
      vec4(up, 0.f),
      vec4(front, 0.f),
      vec4(pos, 1.f));
    const mat4 view = inverse(inverseView);
    const float znear = 0.001f;
    const float zfar = lights.spotLights[iidx].range + 0.001f;
    const float invext = 1.f / tan(-lights.spotLights[iidx].outerConeAngle * 0.5f);
    const float invZRng = 1.f / (zfar - znear);
    const mat4 proj = mat4(
      vec4(invext, 0.f, 0.f, 0.f),
      vec4(0.f, invext, 0.f, 0.f),
      vec4(0.f, 0.f, zfar * invZRng, 1.f),
      vec4(0.f, 0.f, -znear * zfar * invZRng, 0.f));

    mats.spotLightMats[iidx] = proj * view;
  }
  else
  {
    const uint iidx = idx - POINT_MAT_CNT - SPOT_MAT_CNT;
    const uint lidx = iidx / CSM_CASCADE_COUNT;
    const uint cidx = iidx - lidx;
    // @TODO
  }
}
