#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "defs.h"
#include "geometry.h"

layout(local_size_x = BASE_WORK_GROUP_SIZE) in;

layout(binding = 0, set = 0) buffer bboxes_t
{
  BBoxAsOrdUints bboxes[];
};

layout(push_constant) uniform params_t
{
  uint baseBboxId;
  uint bboxCount;
} params;

void main(void)
{
  if (gl_GlobalInvocationID.x < params.bboxCount)
  {
    const BBoxAsOrdUints bb = bboxes[params.baseBboxId + gl_GlobalInvocationID.x];
    bboxes[params.baseBboxId + gl_GlobalInvocationID.x].min.y = floatBitsToUint(ordered_uint_to_float(bb.min.y));
    bboxes[params.baseBboxId + gl_GlobalInvocationID.x].max.y = floatBitsToUint(ordered_uint_to_float(bb.max.y));
  }
}

