#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "dispatch.h"
#include "defs.h"

#include "grass.comp.inc"

layout(binding = 0, set = 0) readonly buffer gen_t
{
  GRASS_GEN_DATA_MEMBERS
};

layout(binding = 1, set = 0) buffer cmd_t
{
  IndirectDispatchCommand command;
};

void main(void)
{
  if (gl_GlobalInvocationID.x == 0)
  {
    command.wgX = get_linear_wg_count_disp(chunkCount, BASE_WORK_GROUP_SIZE);
  }
}
