#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "defs.h"
#include "terrain.h"
#include "constants.h"
#include "draw.h"

#include "grass.comp.inc"
#include "common.frag.inc"

layout(local_size_x = BASE_WORK_GROUP_SIZE) in;

layout(binding = 8, set = 0) uniform constants_t
{
  Constants constants;
};

layout(binding = 9, set = 0) uniform view_params_t
{
  ViewParams viewParams;
};

layout(binding = 10, set = 0) readonly buffer gen_t
{
  GRASS_GEN_DATA_MEMBERS
};

layout(binding = 11, set = 0) readonly buffer template_t
{
  vec2 templateGrassPositions[];
};

layout(binding = 12, set = 0) buffer cmd_t
{
  IndirectCommand command;
};

layout(binding = 13, set = 0) writeonly buffer instances_t
{
  GrassInstance culledInstances[];
};

#include "culling.comp.inc"
#include "terrain_mesh.glsl.inc"

layout(push_constant) uniform params_t
{
  uint detailId;
} params;

float wind_oscillator(float time, vec2 worldPos)
{
  float phase = dot(worldPos, vec2(0.3, 0.7));
  float w = 0.0;
  w += 0.50 * sin(time * 1.0000 + phase);
  w += 0.25 * sin(time * 2.7183 + phase * 1.7);
  w += 0.10 * sin(time * 7.3891 + phase * 2.3);
  return w;
}

void main(void)
{
  const uint vegTypeId = terrainSource.details[params.detailId].vegetationId;
  const TerrainVegetationRule rule = terrainSource.vegetationTypes[vegTypeId];

  uint chunkId = gl_GlobalInvocationID.x / rule.templateBufferSize;
  if (chunkId >= chunkCount)
    return;

  vec2 chunkPosPlanar = chunkOrigins[chunkId];
  uint templateId = rule.templateBufferOffset + (gl_GlobalInvocationID.x - chunkId * rule.templateBufferSize);
  vec2 templatePos = templateGrassPositions[templateId];

  int oriId = basic_noise_int(chunkPosPlanar, 0, 3);
  if ((oriId & 1) != 0)
    templatePos.x = VEGETATION_CHUNK_SIZE - templatePos.x;
  if ((oriId & 2) != 0)
    templatePos.y = VEGETATION_CHUNK_SIZE - templatePos.y;

  vec2 grassPosPlanar = chunkPosPlanar + templatePos;
  vec2 grassPosPlanarRelToClipmap = grassPosPlanar - constants.toroidalUpdatePlayerWorldPos;

  vec4 matdata = load_matdata_clipmap(grassPosPlanarRelToClipmap);
  uint detailMask = floatBitsToUint(matdata.w);
  if ((detailMask & (1 << params.detailId)) == 0)
    return;
  uint otherDetailsMask = (detailMask & ~(1 << params.detailId));
  if (otherDetailsMask != 0)
  {
    uint conflictingCount = bitCount(otherDetailsMask);
    if (basic_noise_int(grassPosPlanar, 0, int(terrainSource.detailCount)) < conflictingCount)
      return;
  }

  float height = sample_geom_clipmap(grassPosPlanarRelToClipmap);
  vec3 grassPos = vec3(grassPosPlanar.x, height, grassPosPlanar.y);

  float instDist = length(viewParams.mViewPos - grassPos);
  if (instDist > constants.vegetationRenderingDistance)
    return;

  const mat4 instMat = translation(grassPos);
  const float r = rule.radius * 1.5f; // for wind
  const BBox bbox = {
    vec4(-r, -rule.height * GRASS_SANK_PORTION        , -r, 1.f),
    vec4( r,  rule.height * (1.f - GRASS_SANK_PORTION),  r, 1.f)};
  InstanceViewRelatedData payload;

  if (instance_is_in_view(bbox, instMat, constants.cullingMode, payload))
  {
    const uint rotAngle = basic_noise_int(grassPos.xz, 0, 359);
    const uint instId = atomicAdd(command.instanceCount, 1);
    culledInstances[instId].pos = grassPos;
    culledInstances[instId].idAndAnglePacked = (rotAngle << GRASS_ID_BITS) | (vegTypeId & GRASS_ID_MASK);
    culledInstances[instId].windOffset = vec3(0.f);

    if (constants.windStrength >= 0.001f)
    {
      float shrinkFactor = min(
        (instDist - constants.vegetationRenderingDistance) /
        (constants.vegetationRenderingDropoffDistance - constants.vegetationRenderingDistance),
        1.f);

      vec2 windVec = grassPos.xz - constants.windOrigin;
      float dist = length(windVec);

      // @TODO: settable
      const float lambda = 0.5f;
      const float plambda = 0.5f;
      const float pscale = 5.f;
      const float relAmp = 0.4f;

      float strengthFalloff = lambda + (1.f - lambda) / (1.f + dist);
      float strengthPeriod = pscale * (plambda + (1.f - plambda) / (1.f + dist));

      // @TODO: more sine waves?
      float strengthOscillation = relAmp * wind_oscillator(strengthPeriod * constants.time, grassPos.xz);

      float windInfluenceAmt = constants.windStrength * (1.f + strengthOscillation) * strengthFalloff;
      vec2 windInfluence = (windVec / dist) * windInfluenceAmt;

      vec3 posOffset = shrinkFactor * vec3(windInfluence.x, -0.5f * (windInfluenceAmt * windInfluenceAmt), windInfluence.y);
      culledInstances[instId].windOffset = posOffset;
    }
  }
}
