#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "defs.h"
#include "terrain.h"
#include "constants.h"

#include "grass.comp.inc"

layout(local_size_x = VEGETATION_CHUNK_CULL_GROUP_DIM, local_size_y = VEGETATION_CHUNK_CULL_GROUP_DIM) in;

layout(binding = 8, set = 0) uniform constants_t
{
  Constants constants;
};

layout(binding = 9, set = 0) uniform view_params_t
{
  ViewParams viewParams;
};

layout(binding = 10, set = 0) buffer gen_t
{
  GRASS_GEN_DATA_MEMBERS
};

#include "culling.comp.inc"

void main(void)
{
  if (gl_GlobalInvocationID.x >= VEGETATION_GRID_EXTENT || gl_GlobalInvocationID.y >= VEGETATION_GRID_EXTENT)
    return;

  const ivec2 chunkId = ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y) - VEGETATION_GRID_EXTENT / 2;
  const vec2 chunkPos = constants.toroidalUpdatePlayerWorldPos + vec2(chunkId) * VEGETATION_CHUNK_SIZE;

  const mat4 instMat = translation(vec3(chunkPos.x, 0.f, chunkPos.y));
  const BBox bbox = {vec4(0.f, -10000.f, 0.f, 1.f), vec4(VEGETATION_CHUNK_SIZE, 10000.f, VEGETATION_CHUNK_SIZE, 1.f)};
  InstanceViewRelatedData payload;

  if (instance_is_in_view(bbox, instMat, constants.cullingMode, payload))
  {
    const uint destId = atomicAdd(chunkCount, 1);
    chunkOrigins[destId] = chunkPos;
  }
}
