#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "defs.h"
#include "terrain.h"

#include "grass.comp.inc"

layout(local_size_x = VEGETATION_GRID_EXTENT, local_size_y = VEGETATION_GRID_EXTENT) in;

layout(binding = 8, set = 0) uniform constants_t
{
  Constants constants;
};

layout(binding = 9, set = 0) uniform view_params_t
{
  ViewParams viewParams;
};

layout(binding = 10, set = 0) buffer gen_t
{
  GrassGenData genData;
};

void main(void)
{
  if (gl_GlobalInvocationID.x >= VEGETATION_GRID_EXTENT || gl_GlobalInvocationID.y >= VEGETATION_GRID_EXTENT)
    return;

  ivec2 chunkId = ivec2(gl_GlobalInvocationID.xy) - VEGETATION_GRID_EXTENT / 2;
  vec2 chunkPos = constants.toroidalUpdatePlayerWorldPos + vec2(chunkId) * VEGETATION_CHUNK_SIZE;

  const vec2 chunkCorners =
  {
    chunkPos,
    chunkPos + vec2(VEGETATION_CHUNK_SIZE, 0.f),
    chunkPos + vec2(0.f, VEGETATION_CHUNK_SIZE),
    chunkPos + vec2(VEGETATION_CHUNK_SIZE, VEGETATION_CHUNK_SIZE)
  };

  if (viewParams.type == VIEW_TYPE_PERSPECTIVE)
  {
    // @TODO
  }
  else // VIEW_TYPE_ORTHO
  {
    // @TODO
  }
}
