#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "defs.h"
#include "geometry.h"
#include "terrain.h"
#include "constants.h"

layout(local_size_x = BASE_WORK_GROUP_SIZE) in;

layout(binding = 0, set = 0) uniform usampler2D cellMinHeightLut;
layout(binding = 1, set = 0) uniform usampler2D cellMaxHeightLut;

layout(binding = 2, set = 0) buffer bboxes_t
{
  BBoxAsOrdUints bboxes[];
};

layout(binding = 7, set = 0) uniform terrain_source_t
{
  TerrainSourceData source;
};
layout(binding = 8, set = 0) uniform constants_t
{
  Constants constants;
};

layout(push_constant) uniform params_t
{
  uint baseBboxId;
  uint bboxCount;
} params;

void main(void)
{
  const uint cellsPerSmallestChunkSide = uint(round(TERRAIN_SMALLEST_CHUNK_DIM / source.cellDim));
  const uint cellsPerSmallestChunk = cellsPerSmallestChunkSide * cellsPerSmallestChunkSide;
  
  const uint cellsInLevel0 = TERRAIN_FIRST_LEVEL_CHUNKS * cellsPerSmallestChunk; 

  const uint cellGlobId = gl_GlobalInvocationID.x;

  uint chunkId;
  ivec2 inChunkId;
  vec2 chunkPosRelToPlayer;
  if (cellGlobId < cellsInLevel0)
  {
    chunkId = cellGlobId / cellsPerSmallestChunk;
    const uint inChunkIdLinear = cellGlobId - chunkId * cellsPerSmallestChunk;
    inChunkId = ivec2(inChunkIdLinear % cellsPerSmallestChunkSide, inChunkIdLinear / cellsPerSmallestChunkSide);
    chunkPosRelToPlayer = vec2(
      float(chunkId % TERRAIN_CHUNKS_LEVEL_DIM) * TERRAIN_SMALLEST_CHUNK_DIM - CLIPMAP_EXTENT_STEP,
      float(chunkId / TERRAIN_CHUNKS_LEVEL_DIM) * TERRAIN_SMALLEST_CHUNK_DIM - CLIPMAP_EXTENT_STEP);
  }
  else
  {
    const uint afterId = cellGlobId - cellsInLevel0;
    const uint levelIndicator = afterId / (12 * 4 * cellsPerSmallestChunk);
    const uint lsb = findMSB(levelIndicator);
    const uint level = lsb == -1 ? 1 : ((lsb / 2) + 2);

    const uint allLevelsCountTemplate = 0x55555555; // 0b01010101010101010101010101010101
    const uint prevLevelsSRingCount = ((1 << ((level - 1) * 2)) - 1) & allLevelsCountTemplate;
    const uint prevLevelsChunkCount = prevLevelsSRingCount * 12 * 4;
    const uint prevLevelsCellCount = prevLevelsChunkCount * cellsPerSmallestChunk;

    const uint inLevelCellId = afterId - prevLevelsCellCount;
    const uint levelChunkCellSide = cellsPerSmallestChunkSide * (1 << level);
    const uint levelChunkCells = levelChunkCellSide * levelChunkCellSide;
    const uint inLevelChunkId = inLevelCellId / levelChunkCells;
    const uint inChunkCellLinearId = inLevelCellId - levelChunkCells * inLevelChunkId;

    chunkId = inLevelChunkId + prevLevelsChunkCount;
    inChunkId = ivec2(inChunkCellLinearId % levelChunkCellSide, inChunkCellLinearId / levelChunkCellSide);

    const vec2 chunkExt = vec2(float(1 << level) * float(TERRAIN_SMALLEST_CHUNK_DIM));
    const vec2 levelExt = float(TERRAIN_CHUNKS_LEVEL_DIM) * chunkExt * 0.5f;

    if (inLevelChunkId < TERRAIN_CHUNKS_LEVEL_DIM)
    {
      chunkPosRelToPlayer = vec2(float(inLevelChunkId) * chunkExt.x - levelExt.x, -levelExt.y);
    }
    else if (inLevelChunkId < TERRAIN_OTHER_LEVELS_CHUNKS - TERRAIN_CHUNKS_LEVEL_DIM)
    {
      const uint yId = (chunkId - TERRAIN_CHUNKS_LEVEL_DIM) >> 1;
      const uint xId = (chunkId - TERRAIN_CHUNKS_LEVEL_DIM) & 1;
      chunkPosRelToPlayer = vec2(
        xId == 1 ? (-levelExt.x) : (levelExt.x - chunkExt.x),
        chunkExt.y * float(yId + 1) - levelExt.y);
    }
    else
    {
      chunkPosRelToPlayer = vec2(
        float(inLevelCellId - TERRAIN_OTHER_LEVELS_CHUNKS + TERRAIN_CHUNKS_LEVEL_DIM) * chunkExt.x - levelExt.x,
        levelExt.y - chunkExt.y);
    }
  }

  const vec2 cellPosRelToPlayer = chunkPosRelToPlayer + vec2(inChunkId) * source.cellDim;
  const vec2 cellPos = cellPosRelToPlayer + constants.toroidalUpdatePlayerWorldPos;
  const vec2 cellMapBase = floor(source.rangeMin.xz / source.cellDim) * source.cellDim;
  const vec2 cellMapTop = ceil(source.rangeMax.xz / source.cellDim) * source.cellDim;

  const vec2 cellMapUv = (cellPos - cellMapBase) / (cellMapTop - cellMapBase);
  const float cellMinZRel = ordered_uint_to_float(textureLod(cellMinHeightLut, cellMapUv, 0.f).x);
  const float cellMaxZRel = ordered_uint_to_float(textureLod(cellMaxHeightLut, cellMapUv, 0.f).x);

  const float cellMinZ = source.rangeMin.y + cellMinZRel * (source.rangeMax.y - source.rangeMin.y);
  const float cellMaxZ = source.rangeMin.y + cellMaxZRel * (source.rangeMax.y - source.rangeMin.y);

  if (chunkId < params.bboxCount)
  {
    // @PERF: this may be slow on larger chunks
    atomicMin(bboxes[params.baseBboxId + chunkId].min.y, float_to_ordered_uint(cellMinZ));
    atomicMax(bboxes[params.baseBboxId + chunkId].max.y, float_to_ordered_uint(cellMaxZ));
  }
}
