#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "defs.h"
#include "terrain.h"

layout(local_size_x = BASE_WORK_GROUP_SIZE) in;

layout(binding = 0, set = 0) writeonly buffer chunk_height_bounds_data_t
{
  ChunkHeightBoundsData chunkHeightBoundsData;
};

void clear_entry(out HeightBounds entry)
{
  entry.minZOrdUint = SHADER_UINT_MAX;
  entry.maxZOrdUint = 0;
}

void main(void)
{
  const uint id = gl_GlobalInvocationID.x;
  if (id < TERRAIN_FIRST_LEVEL_CHUNKS)
  {
    clear_entry(chunkHeightBoundsData.firstLevel[id]);
  }
  else if (id < TERRAIN_TOTAL_CHUNK_COUNT)
  {
    const uint iid = id - TERRAIN_FIRST_LEVEL_CHUNKS;
    const uint lid = iid / TERRAIN_OTHER_LEVELS_CHUNKS;
    const uint cid = iid - TERRAIN_OTHER_LEVELS_CHUNKS * lid;
    clear_entry(chunkHeightBoundsData.otherLevels[lid][cid]);
  }
}
