#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "defs.h"
#include "geometry.h"
#include "constants.h"
#include "terrain.h"

layout(local_size_x = BASE_WORK_GROUP_SIZE) in;

layout(binding = 0, set = 0) buffer bboxes_t
{
  BBox bboxes[];
};

layout(binding = 1, set = 0) readonly buffer chunk_height_bounds_data_t
{
  ChunkHeightBoundsData chunkHeightBoundsData;
};

layout(binding = 8, set = 0) uniform constants_t
{
  Constants constants;
};

void transfer_entry(HeightBounds hb, inout BBox box)
{
  box.min.y = ordered_uint_to_float(hb.minZOrdUint);
  box.max.y = ordered_uint_to_float(hb.maxZOrdUint);
}

void main(void)
{
  const uint id = gl_GlobalInvocationID.x;
  const uint bid = id + constants.terrainFirstInstance;
  if (id < TERRAIN_FIRST_LEVEL_CHUNKS)
  {
    transfer_entry(chunkHeightBoundsData.firstLevel[id], bboxes[bid]);
  }
  else if (id < TERRAIN_TOTAL_CHUNK_COUNT)
  {
    const uint iid = id - TERRAIN_FIRST_LEVEL_CHUNKS;
    const uint lid = iid / TERRAIN_OTHER_LEVELS_CHUNKS;
    const uint cid = iid - TERRAIN_OTHER_LEVELS_CHUNKS * lid;
    transfer_entry(chunkHeightBoundsData.otherLevels[lid][cid], bboxes[bid]);
  }
}

