#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "lights.h"
#include "geometry.h"

layout(binding = 0, set = 0) writeonly buffer light_mats_t
{
  LightMatrices lightMats;
};

layout(binding = 9, set = 0) uniform view_params_t
{
  ViewParams viewParams;
};
layout(binding = 10, set = 0) readonly buffer view_data_t
{
  ViewData viewData;
};

layout(push_constant) uniform params_t
{
  uint lightId;
} params;

void main(void)
{
  const mat4 correctedMat = calc_adjusted_viewproj_mat(viewParams, viewData);
  if (params.lightId < POINT_LIGHT_BUF_SIZE * 6)
  {
    const uint idx = params.lightId;
    const uint lidx = idx / 6;
    const uint fidx = idx - lidx * 6;
    lightMats.pointLightMats[lidx][fidx] = correctedMat;
  }
  else if (params.lightId < POINT_LIGHT_BUF_SIZE * 6 + SPOT_LIGHT_BUF_SIZE)
  {
    const uint idx = params.lightId - POINT_LIGHT_BUF_SIZE * 6;
    lightMats.spotLightMats[idx] = correctedMat;
  }
  else if (
    params.lightId <
    POINT_LIGHT_BUF_SIZE * 6 + SPOT_LIGHT_BUF_SIZE + DIRECTIONAL_LIGHT_BUF_SIZE * CSM_CASCADE_COUNT)
  {
    const uint idx = params.lightId - POINT_LIGHT_BUF_SIZE * 6 - SPOT_LIGHT_BUF_SIZE;
    const uint lidx = idx / CSM_CASCADE_COUNT;
    const uint cidx = idx - lidx * CSM_CASCADE_COUNT;
    lightMats.directionalLightMats[lidx][cidx] = correctedMat;
  }
}
