#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "draw.h"
#include "constants.h"
#include "terrain.h"

#include "common.frag.inc"


layout(local_size_x = CLIPMAP_WORK_GROUP_SIZE) in;

layout(binding = 0, set = 0, r32f) uniform writeonly image2D geom[CLIPMAP_LEVEL_COUNT];
layout(binding = 1, set = 0, rgba32f) uniform writeonly image2D normal[CLIPMAP_LEVEL_COUNT];
layout(binding = 2, set = 0, rgba32f) uniform writeonly image2D albedo[CLIPMAP_LEVEL_COUNT];
layout(binding = 3, set = 0, rgba32f) uniform writeonly image2D matdata[CLIPMAP_LEVEL_COUNT];

layout(binding = 7, set = 0) uniform terrain_source_t
{
  TerrainSourceData source;
};
layout(binding = 8, set = 0) uniform constants_t
{
  Constants constants;
};

layout(push_constant) uniform params_t
{
  uint level;
} params;

#include "material_mesh.glsl.inc"

float sstep(float x)
{
  float x2 = x * x;
  float x3 = x2 * x;
  return 3 * x2 - 2 * x3;
}

float slstep(float x)
{
  return (sstep(x) + x) * 0.5f;
}

struct ContinentHeightAdjustment
{
  float relHeightContractionCoeff;
  float relHeightDisplacement;
};

ContinentHeightAdjustment get_height_adjustment_from_continent(vec2 worldPos)
{
  ContinentHeightAdjustment adj;
  adj.relHeightContractionCoeff = 1.f;
  adj.relHeightDisplacement = 0.f;
  if (source.continentType == 1) // Circle, couldn't be fucked with an enum
  {
    float d = length(worldPos - source.continentCircleCenter);
    float tbase =
      (d - source.continentCircleInnerOuterRad.x) /
      (source.continentCircleInnerOuterRad.y - source.continentCircleInnerOuterRad.x);
    float t = clamp(tbase, 0.f, 1.f);
    float st = slstep(t);
    adj.relHeightDisplacement +=
      st * (source.continentOceanBottom - source.rangeMin.y) /
      (source.rangeMax.y - source.rangeMin.y);
    adj.relHeightContractionCoeff -= st;
    adj.relHeightContractionCoeff *= adj.relHeightContractionCoeff;
    adj.relHeightContractionCoeff = 0.15f + 0.85f * adj.relHeightContractionCoeff;
  }
  return adj;
}

float to_abs_height(float h)
{
  return source.rangeMin.y + h * (source.rangeMax.y - source.rangeMin.y);
}

vec2 wc_to_uv(vec2 worldCoord)
{
  const vec3 terrainExtent = source.rangeMax - source.rangeMin;
  return (worldCoord - source.rangeMin.xz) / terrainExtent.xz;
}

vec2 uv_to_wc(vec2 uv)
{
  const vec3 terrainExtent = source.rangeMax - source.rangeMin;
  return uv * terrainExtent.xz + source.rangeMin.xz;
}

float sample_rel_height_uv(vec2 uv, vec2 worldUv)
{
  float relHeight = 0.f;
  if (source.heightmapTexSmp != NO_TEXTURE_ID)
    relHeight = sample_bindless_tex_bicubic_lod(source.heightmapTexSmp, uv, 0.f).x;

  // @TEMP just scale back into [0, 1]
  relHeight *= 1.f - 2.f * constants.terrainNoiseRelHeightAmp;
  relHeight += constants.terrainNoiseRelHeightAmp;

  // @TODO seed
  relHeight +=
    simplex_noise(worldUv * constants.terrainNoisePeriod) *
    constants.terrainNoiseRelHeightAmp;

  return relHeight;
}

float sample_height_uv(vec2 uv, vec2 worldUv, vec2 worldCoord)
{
  ContinentHeightAdjustment continentAdj = get_height_adjustment_from_continent(worldCoord);
  float h = sample_rel_height_uv(uv, worldUv);
  h *= continentAdj.relHeightContractionCoeff;
  h += continentAdj.relHeightDisplacement;
  h = to_abs_height(h);
  return h;
}

float sample_rel_height(vec2 worldCoord)
{
  const vec3 terrainExtent = source.rangeMax - source.rangeMin;
  const vec2 uv = wc_to_uv(worldCoord);
  ContinentHeightAdjustment continentAdj = get_height_adjustment_from_continent(worldCoord);
  float h = sample_rel_height_uv(uv, uv * terrainExtent.xz);
  h *= continentAdj.relHeightContractionCoeff;
  h += continentAdj.relHeightDisplacement;
  return h;
}

vec4 sample_splatmask(vec2 worldCoord)
{
  vec4 splatmask = vec4(0.f);
  if (source.splattingMaskTexSmp != NO_TEXTURE_ID)
    splatmask = sample_bindless_tex_bicubic_lod(source.splattingMaskTexSmp, wc_to_uv(worldCoord), 0.f);
  return splatmask;
}

vec3 generate_normal(vec2 worldCoord)
{
  const float wjitter = 1.f; // dx and dy

  const vec3 terrainExtent = source.rangeMax - source.rangeMin;
  const vec2 uv = (worldCoord - source.rangeMin.xz) / terrainExtent.xz;
  const vec2 jitter = wjitter / terrainExtent.xz;

  const vec2 xl2 = worldCoord - vec2(wjitter, 0.f);
  const vec2 xg2 = worldCoord + vec2(wjitter, 0.f);
  const vec2 zl2 = worldCoord - vec2(0.f, wjitter);
  const vec2 zg2 = worldCoord + vec2(0.f, wjitter);

  const vec2 xluv = uv - vec2(jitter.x, 0.f);
  const vec2 xguv = uv + vec2(jitter.x, 0.f);
  const vec2 zluv = uv - vec2(0.f, jitter.y);
  const vec2 zguv = uv + vec2(0.f, jitter.y);

  const float xl = sample_height_uv(xluv, xluv * terrainExtent.xz, xl2);
  const float xg = sample_height_uv(xguv, xguv * terrainExtent.xz, xg2);
  const float zl = sample_height_uv(zluv, zluv * terrainExtent.xz, zl2);
  const float zg = sample_height_uv(zguv, zguv * terrainExtent.xz, zg2);

  // central numeric differentiation
  return normalize(vec3(2.f * (xl - xg), 4.f, 2.f * (zl - zg)));
}

struct SampledDetail
{
  float h;
  float w;
  vec3 n;
  vec3 color;
  vec3 matData; // Ok to interpolate, cuz mat type is verified to be the same
};

void main(void)
{
  const uint pix = gl_GlobalInvocationID.x;

  const vec2 worldOffset = constants.toroidalOffset;
  const vec2 worldPos = constants.toroidalUpdatePlayerWorldPos;

  ivec2 dims = calculate_toroidal_dims(worldOffset, params.level);

  uint minx = 0, miny = 0;
  if (dims.x < 0)
  {
    dims.x = -dims.x;
    minx = CLIPMAP_RESOLUTION - dims.x;
  }
  if (dims.y < 0)
  {
    dims.y = -dims.y;
    miny = CLIPMAP_RESOLUTION - dims.y;
  }

  const int horizontalPatchSize = CLIPMAP_RESOLUTION * dims.y;
  const int verticalPatchSize = (CLIPMAP_RESOLUTION - dims.y) * dims.x;

  ivec2 flatImgCoord = ivec2(0);
  if (pix < horizontalPatchSize)
  {
    flatImgCoord = ivec2(
      pix % CLIPMAP_RESOLUTION,
      miny + (pix / CLIPMAP_RESOLUTION));
  }
  else if (pix < horizontalPatchSize + verticalPatchSize)
  {
    const uint ppix = pix - horizontalPatchSize;  
    flatImgCoord = ivec2(minx + (ppix % dims.x), ppix / dims.x);
    if (miny == 0) flatImgCoord.y += dims.y;
  }
  else
  {
    return;
  }

  const vec2 flatUv = vec2(flatImgCoord) / float(CLIPMAP_RESOLUTION);

  const float clipmapWorldExtent = float(1 << params.level) * CLIPMAP_EXTENT_STEP;
  const float clipmapWorldSize = clipmapWorldExtent * 2.f;

  const vec2 worldCoord = worldPos + (flatUv - 0.5f) * clipmapWorldSize;

  const ivec2 toroidalScrolloff = 
    ivec2((fract(worldPos / clipmapWorldSize) - 0.5f) * CLIPMAP_RESOLUTION);

  const ivec2 destImageCoord = 
    (flatImgCoord + toroidalScrolloff + CLIPMAP_RESOLUTION) % CLIPMAP_RESOLUTION;

  SampledDetail details[TERRAIN_MAX_DETAILS];
  for (uint i = 0; i < source.detailCount; ++i)
  {
    details[i].h = 0.f;
    details[i].w = 0.f;
    details[i].n = vec3(0.f);
    details[i].color = vec3(0.f);
    details[i].matData = vec3(0.f);
  }

  uint detailMask = 0;
  float h = 0.f;
  vec3 n = vec3(0.f);
  vec3 color = vec3(0.f);
  vec3 matData = vec3(0.f);

  {
    float rh = sample_rel_height(worldCoord);
    vec4 splatmask = sample_splatmask(worldCoord);

    // @TODO: on one hand, displacement should participate in normal gen.
    // On the other hand, it means doing the detail loop for each of the 4
    // pixels. Either way, rn disp looks like shit
    const vec3 baseN = generate_normal(worldCoord);

    // U gradient is vec2(1, 0) => take tang as the projection of vec(1,0)
    // onto the orthogonal plane to the normal
    const vec3 grad = vec3(1.f, 0.f, 0.f);
    const vec3 gnproj = baseN * dot(grad, baseN);
    const vec4 tang = vec4(normalize(grad - gnproj), 1.f); // @TODO: is this correct?

    float maxw = -10000.f;

    for (uint i = 0; i < source.detailCount; ++i)
    {
      const vec2 scale = source.details[i].uvScale; 
      const vec2 uv = worldCoord / scale; 

      float splatW = 1.f; 
      float rangeW = 1.f; 
      if ((source.details[i].flags & TERRAIN_DETAIL_USE_MASK_FLAG) != 0)
      {
        splatW = get_v4_component(splatmask, source.details[i].splattingCompId);
      }
      if ((source.details[i].flags & TERRAIN_DETAIL_USE_RH_RANGE_FLAG) != 0)
      {
        float hForRange = rh + 0.05f * (basic_noise(float(i) * (worldCoord + uv)) - 0.5f);
        float ld = max(source.details[i].heightRange.x - hForRange, 0.f);
        float hd = max(hForRange - source.details[i].heightRange.y, 0.f);

        // @TODO: correct when there can be another source of w (splatting)
        float lw = 1.f - min(ld / TERRAIN_DETAIL_LEVEL_FALLOFF, 1.f);
        float hw = 1.f - min(hd / TERRAIN_DETAIL_LEVEL_FALLOFF, 1.f);

        rangeW = sstep(min(lw, hw));
      }

      float w = min(splatW * rangeW, 1.f);

      if (w > SHADER_EPSILON)
      {
        vec2 ddxy = vec2(CLIPMAP_LEVEL_WSIZE(params.level)) / scale;
        float lod = log2(max(ddxy.x, ddxy.y));

        // @TODO: bring this back into one call
        const vec3 detCol = get_pixel_albedo_lod(source.details[i].matId, uv, lod).xyz;
        const vec3 detMatdata = get_pixel_matdata_lod(source.details[i].matId, uv, lod);
        const vec3 detNorm = get_pixel_normal_lod(source.details[i].matId, baseN, tang, uv, lod);

        float h = 0.f;
        {
          const uint matId = source.details[i].matId;
          if (matId != NO_MATERIAL)
          {
            const TexSmpIdPair dispTexId = materialParams[matId].heightDisplacementTexSmp;
            const float dispCoeff = materialParams[matId].displacementCoeff;

            if (dispTexId != NO_TEXTURE_ID && abs(dispCoeff) > SHADER_EPSILON)
            {
              h = sample_bindless_tex_lod(dispTexId, uv, float(params.level)).x * dispCoeff;
            }
          }
        }

        w += h;

        details[i].h = h;
        details[i].w = w;
        details[i].n = detNorm;
        details[i].color = detCol;
        details[i].matData = detMatdata;

        if (w > maxw)
        {
          maxw = w;
        }
      }
    }

    if (constants.drawTerrainSplattedDetail == 0)
    {
      color = vec3(0.2, 0.8, 0.5);
      matData = vec3(float(MATERIAL_DIFFUSE), 0.f, 0.f);
      n = baseN;
    }
    else
    {
      const float depth = 0.2;
      maxw -= depth;

      float totw = 0.f;
      float disp = 0.f;

      for (uint i = 0; i < source.detailCount; ++i)
      {
        details[i].w = max(details[i].w - maxw, 0.f);
        disp += details[i].h * details[i].w;
        n += details[i].n * details[i].w;
        color += details[i].color * details[i].w;
        matData += details[i].matData * details[i].w;
        totw += details[i].w;
      }

      for (uint i = 0; i < source.detailCount; ++i)
      {
        if (details[i].w / totw > 0.95)
          detailMask |= (1 << i);
      }
      
      //rh += disp / totw;
      color /= totw;
      matData /= totw;
      n = normalize(n / totw);
    }

    h = to_abs_height(rh);
  }

  imageStore(geom[params.level], destImageCoord, vec4(h));
  imageStore(normal[params.level], destImageCoord, vec4(n, 1.f));
  imageStore(albedo[params.level], destImageCoord, vec4(color, 1.f));
  imageStore(matdata[params.level], destImageCoord, vec4(matData, uintBitsToFloat(detailMask)));
}
