#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "fog.h"
#include "constants.h"
#include "geometry.h"

layout(local_size_x = FOG_WORKGROUP_DIM, local_size_y = FOG_WORKGROUP_DIM, local_size_z = 1) in;

layout(binding = 0, set = 0, rgba16f) uniform writeonly image2D fogHalfres;
layout(binding = 1, set = 0) uniform sampler2D gbufDepth;
layout(binding = 2, set = 0) uniform sampler3D perlinNoise;

layout(binding = 6, set = 0) uniform fog_source_t
{
  FogSourceData source;
};
layout(binding = 8, set = 0) uniform constants_t
{
  Constants constants;
};

layout(binding = 9, set = 0) uniform view_params_t
{
  ViewParams viewParams;
};
layout(binding = 10, set = 0) readonly buffer view_data_t
{
  ViewData viewData;
};

layout(binding = 11, set = 0) uniform light_data_t
{
  UniformLights lights;
};

layout(binding = 12, set = 0) readonly buffer light_mats_t
{
  LightMatrices mats;
};

#include "bindless.glsl.inc"
#include "lights.glsl.inc"

float perlin(vec3 p)
{
  return textureLod(perlinNoise, p / 32.f, 0.f).x * 2.f - 1.f;
}

float fbm(vec3 p, int octaves)
{
  float value = 0.f;
  float amplitude = 0.5f;

  for (int i = 0; i < octaves; i++)
  {
    value += amplitude * perlin(p);

    p *= 2.f;
    amplitude *= 0.5f;
  }

  return 0.5f * value + 0.5f;
}

float density_noise(vec3 p, float rng_min, float rng_max, int n, float scale, float wind_inf)
{
  const vec2 wind2d = -constants.weatherData.windDirection * constants.weatherData.windStrength;
  const vec3 wind = vec3(wind2d.x, 0.f, wind2d.y) * constants.time;
  float base = fbm((p + wind * wind_inf) / scale, n);
  return smoothstep(rng_min, rng_max, base);
}

float density_base(vec3 p)
{
  float height = exp(-max(p.y - constants.weatherData.fogHBase, 0.f) * constants.weatherData.fogHC);
  return height * constants.weatherData.fogRho0;
}

float density(vec3 p, float dist)
{
  const vec2 wind2d = -constants.weatherData.windDirection * constants.weatherData.windStrength;
  const vec3 wind = vec3(wind2d.x, 0.f, wind2d.y) * constants.time;
  float shapeFaded = 1.f;
  if (constants.weatherData.fogShapeScale > SHADER_EPSILON)
  {
    float shapeFadeout = smoothstep(
      0.f, 1.f,
      (dist - constants.weatherData.fogShapeFadeoutStart) / constants.weatherData.fogShapeFadeoutSize);
    float shape = 1.f;
    if (shapeFadeout < 0.9999f)
    {
      shape = density_noise(
        p,
        constants.weatherData.fogShapeRngMin,
        constants.weatherData.fogShapeRngMax,
        3,
        constants.weatherData.fogShapeScale,
        constants.weatherData.fogShapeWindInfluence);
    }
    shapeFaded = mix(shape, 1.f, shapeFadeout);
  }
  return density_base(p) * shapeFaded;
}

void main(void)
{
  ivec2 imCoord = ivec2(gl_GlobalInvocationID.xy);
  ivec2 imSize = ivec2(constants.mainTargetResolution) / 2;

  if (imCoord.x >= imSize.x || imCoord.y >= imSize.y)
    return;

  const bool scatterAllLights = constants.fogSceneLightsScatterCoeff >= SHADER_EPSILON;

  const vec2 invaspect = vec2(1.f / viewParams.mProj[0][0], 1.f / viewParams.mProj[1][1]);
  const vec2 uv = vec2(2 * imCoord + 1) * constants.mainTargetInverseResolution;
  const vec2 ndcuv = 2.f * uv - 1.f;
  const vec3 ray = vec3(ndcuv * invaspect, 1.f);
  const float raylen = length(ray);
  const vec3 dir = ray / raylen;

  const float clipDepth = textureLod(gbufDepth, uv, 0.f).x;
  const float linearDepth = linearize_z(clipDepth, viewParams, viewData);
  const float worldDepth = raylen * linearDepth;

  const vec3 worldDir = mat3(viewParams.mInverseView) * dir;

  vec3 pos = viewParams.viewPos;
  vec3 vpos = vec3(0.f);
  float stepSize = min(worldDepth / constants.fogRaymarchSteps, constants.fogMaxStepSize);
  vec3 posStep = worldDir * stepSize;
  vec3 vposStep = dir * stepSize;
  vec4 transmitted = vec4(0.f, 0.f, 0.f, 1.f);
  float dist = 0.f;
  float pdd = density(pos, dist);

  for (int s = 0; s < constants.fogRaymarchSteps; ++s)
  {
    float ndd = density(pos, dist);
    float dd = (ndd + pdd) * 0.5f;
    pdd = ndd;
    if (dd < 0.000001f)
    {
      pos += posStep;
      vpos += vposStep;
      dist += stepSize;
      continue;
    }

    float ii = constants.weatherData.fogInscatterC;

    float stp = exp(-dd * stepSize); 
    transmitted.a *= stp;

    if (ii > 0.f)
    {
      CsmCascadeLightingData csmd = get_cascade_data_for_view_pos(vpos, viewParams);
      for (int i = 0; i < (scatterAllLights ? lights.directionalLightsCount : min(1, lights.directionalLightsCount)); ++i)
      {
        LightData ld = calculate_directional_light_data(i, pos, csmd, SHADOW_TECHNIQUE_SIMPLE);
        vec3 inscatter = ii * ld.intensity * ld.shadow; // * phase
        transmitted.rgb += transmitted.a * inscatter * stp;
      }

      for (int i = 0; i < (scatterAllLights ? lights.pointLightsCount : 0); ++i)
      {
        LightData ld = calculate_point_light_data(i, pos, SHADOW_TECHNIQUE_SIMPLE);
        vec3 inscatter = ii * ld.intensity * ld.shadow * constants.fogSceneLightsScatterCoeff; // * phase
        transmitted.rgb += transmitted.a * inscatter * stp;
      }
      for (int i = 0; i < (scatterAllLights ? lights.spotLightsCount : 0); ++i)
      {
        LightData ld = calculate_spot_light_data(i, pos, SHADOW_TECHNIQUE_SIMPLE);
        vec3 inscatter = ii * ld.intensity * ld.shadow * constants.fogSceneLightsScatterCoeff; // * phase
        transmitted.rgb += transmitted.a * inscatter * stp;
      }
    }

    pos += posStep;
    vpos += vposStep;
    dist += stepSize;
  }

  float finalTracedLinearDepth = vpos.z;
  float finDepth = min(linearDepth, viewParams.viewFrustum.farZ);
  if (finDepth > finalTracedLinearDepth)
  {
    vec3 startPoint = pos;
    vec3 endPoint = viewParams.viewPos + (pos - viewParams.viewPos) * (finDepth / finalTracedLinearDepth);
    float distantStepSize = raylen * (finDepth - finalTracedLinearDepth) / constants.fogDistantSteps;
    vec3 distantStep = worldDir * distantStepSize;
    for (int s = 0; s < constants.fogDistantSteps; ++s)
    {
      transmitted.a *= exp(-density_base(pos) * distantStepSize);
      pos += distantStep;
    }
  }

  imageStore(fogHalfres, imCoord, transmitted);
}
