#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "fog.h"
#include "constants.h"

layout(local_size_x = FOG_WORKGROUP_DIM, local_size_y = FOG_WORKGROUP_DIM, local_size_z = 1) in;

layout(binding = 0, set = 0, rgba32f) uniform image2D hdrTarget;
layout(binding = 1, set = 0) uniform sampler2D fogHalfres;

layout(binding = 6, set = 0) uniform fog_source_t
{
  FogSourceData source;
};
layout(binding = 8, set = 0) uniform constants_t
{
  Constants constants;
};

// @TODO: pull out & reuse
vec4 sample_tex_catmull_rom_5tap(in sampler2D texSmp, in vec2 uv, in vec2 texSize, in float c)
{
  vec4 rtMetrics = vec4(1.0 / texSize.xy, texSize.xy);

  vec2 position = rtMetrics.zw * uv;
  vec2 centerPosition = floor(position - 0.5) + 0.5;
  vec2 f = position - centerPosition;
  vec2 f2 = f * f;
  vec2 f3 = f * f2;


  vec2 w0 = -c * f3 + 2.0 * c * f2 - c * f;
  vec2 w1 = (2.0 - c) * f3 - (3.0 - c) * f2 + 1.0;
  vec2 w2 = -(2.0 - c) * f3 + (3.0 - 2.0 * c) * f2 + c * f;
  vec2 w3 = c * f3 - c * f2;

  vec2 w12 = w1 + w2;
  vec2 tc12 = rtMetrics.xy * (centerPosition + w2 / w12);
  vec4 centerColor = textureLod(texSmp, vec2(tc12.x, tc12.y), 0);

  vec2 tc0 = rtMetrics.xy * (centerPosition - 1.0);
  vec2 tc3 = rtMetrics.xy * (centerPosition + 2.0);
  vec4 color =
    textureLod(texSmp, vec2(tc12.x, tc0.y), 0) * (w12.x * w0.y) +
    textureLod(texSmp, vec2(tc0.x, tc12.y), 0) * (w0.x * w12.y) +
    centerColor * (w12.x * w12.y) +
    textureLod(texSmp, vec2(tc3.x, tc12.y), 0) * (w3.x * w12.y) +
    textureLod(texSmp, vec2(tc12.x, tc3.y), 0) * (w12.x * w3.y);
  float w = (w12.x * w0.y) + (w0.x * w12.y) + (w12.x * w12.y) + (w3.x * w12.y) + (w12.x * w3.y);
  return color / w;
}

vec4 upscale_sample_fog(vec2 uv)
{
  //return textureLod(fogHalfres, uv, 0.f);
  return sample_tex_catmull_rom_5tap(fogHalfres, uv, textureSize(fogHalfres, 0), 0.f);
}

void main(void)
{
  ivec2 imCoord = ivec2(gl_GlobalInvocationID.xy);
  ivec2 imSize = ivec2(constants.mainTargetResolution);

  if (imCoord.x >= imSize.x || imCoord.y >= imSize.y)
    return;

  vec3 baseColor = imageLoad(hdrTarget, imCoord).xyz;
  vec2 uv = vec2(imCoord) * constants.mainTargetInverseResolution;
  vec4 fog = upscale_sample_fog(uv);

  vec3 finalColor = fog.rgb + mix(source.color, baseColor, fog.a);
  imageStore(hdrTarget, imCoord, vec4(finalColor, 1.f));
}

