#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "fog.h"
#include "constants.h"
#include "geometry.h"

layout(local_size_x = FOG_WORKGROUP_DIM, local_size_y = FOG_WORKGROUP_DIM, local_size_z = 1) in;

layout(binding = 0, set = 0, rgba8) uniform writeonly image2D fogHalfres;
layout(binding = 1, set = 0) uniform sampler2D gbufDepth;

layout(binding = 6, set = 0) uniform fog_source_t
{
  FogSourceData source;
};
layout(binding = 8, set = 0) uniform constants_t
{
  Constants constants;
};

layout(binding = 9, set = 0) uniform view_params_t
{
  ViewParams viewParams;
};
layout(binding = 10, set = 0) readonly buffer view_data_t
{
  ViewData viewData;
};

layout(binding = 11, set = 0) uniform light_data_t
{
  UniformLights lights;
};

layout(binding = 12, set = 0) readonly buffer light_mats_t
{
  LightMatrices mats;
};

#include "bindless.glsl.inc"

void main(void)
{
  ivec2 imCoord = ivec2(gl_GlobalInvocationID.xy);
  ivec2 imSize = ivec2(constants.mainTargetResolution) / 2;

  if (imCoord.x >= imSize.x || imCoord.y >= imSize.y)
    return;

  // @TEST
  vec3 color = source.color;
  if (lights.directionalLightsCount > 0)
  {
    vec3 lightColor = lights.directionalLights[0].intensity * lights.directionalLights[0].color;
    if (((imCoord / 64).x + (imCoord / 64).y) % 2 == 1)
      color = lightColor;
  }
  imageStore(fogHalfres, imCoord, vec4(0.5f, color));
}
