#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "fog.h"
#include "constants.h"
#include "geometry.h"

layout(local_size_x = FOG_WORKGROUP_DIM, local_size_y = FOG_WORKGROUP_DIM, local_size_z = 1) in;

layout(binding = 0, set = 0, rgba16f) uniform writeonly image2D fogHalfres;
layout(binding = 1, set = 0) uniform sampler2D gbufDepth;

layout(binding = 6, set = 0) uniform fog_source_t
{
  FogSourceData source;
};
layout(binding = 8, set = 0) uniform constants_t
{
  Constants constants;
};

layout(binding = 9, set = 0) uniform view_params_t
{
  ViewParams viewParams;
};
layout(binding = 10, set = 0) readonly buffer view_data_t
{
  ViewData viewData;
};

layout(binding = 11, set = 0) uniform light_data_t
{
  UniformLights lights;
};

layout(binding = 12, set = 0) readonly buffer light_mats_t
{
  LightMatrices mats;
};

#include "bindless.glsl.inc"
#include "lights.glsl.inc"

const int raymarchSteps = 64;
const float constantDensity = 0.001f;
const float constantInscatter = 0.01f;
const float maxStepSize = 0.25f;

void main(void)
{
  ivec2 imCoord = ivec2(gl_GlobalInvocationID.xy);
  ivec2 imSize = ivec2(constants.mainTargetResolution) / 2;

  if (imCoord.x >= imSize.x || imCoord.y >= imSize.y)
    return;

  const vec2 invaspect = vec2(1.f / viewParams.mProj[0][0], 1.f / viewParams.mProj[1][1]);
  const vec2 uv = vec2(2 * imCoord + 1) * constants.mainTargetInverseResolution;
  const vec2 ndcuv = 2.f * uv - 1.f;
  const vec3 ray = vec3(ndcuv * invaspect, 1.f);
  const float raylen = length(ray);
  const vec3 dir = ray / raylen;

  const float clipDepth = textureLod(gbufDepth, uv, 0.f).x;
  const float linearDepth = linearize_z(clipDepth, viewParams, viewData);
  const float worldDepth = raylen * linearDepth;

  const vec3 worldDir = mat3(viewParams.mInverseView) * dir;

  vec3 pos = viewParams.viewPos; // @TODO: some other starting pos
  vec3 vpos = vec3(0.f);
  float stepSize = min(worldDepth / raymarchSteps, maxStepSize);
  vec3 posStep = worldDir * stepSize;
  vec3 vposStep = dir * stepSize;
  vec4 transmitted = vec4(0.f, 0.f, 0.f, 1.f);
  for (int s = 0; s < raymarchSteps; ++s)
  {
    pos += posStep;
    vpos += vposStep;

    float d = constantDensity;
    float i = constantInscatter;

    float stp = exp(-d * stepSize); 
    transmitted.a *= stp;

    if (lights.directionalLightsCount > 0)
    {
      CsmCascadeLightingData csmd = get_cascade_data_for_view_pos(vpos, viewParams);
      LightData ld = calculate_directional_light_data(0, pos, csmd);
      vec3 inscatter = i * ld.intensity * ld.shadow; // * phase
      transmitted.rgb += transmitted.a * inscatter * (1.f - stp) / d;
    }
  }

  imageStore(fogHalfres, imCoord, transmitted);
}
