#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "draw.h"
#include "constants.h"
#include "terrain.h"

#include "common.frag.inc"


layout(local_size_x = TERRAIN_CHUNK_HBOUNDS_WORK_GROUP_DIM, local_size_y = TERRAIN_CHUNK_HBOUNDS_WORK_GROUP_DIM) in;

layout(binding = 0, set = 0, r32f) uniform readonly image2D geom[CLIPMAP_LEVEL_COUNT];

layout(binding = 1, set = 0) buffer chunk_height_bounds_data_t
{
  ChunkHeightBoundsData chunkHeightBoundsData;
};

layout(binding = 8, set = 0) uniform constants_t
{
  Constants constants;
};

layout(push_constant) uniform params_t
{
  uint level;
} params;

void main(void)
{
  const uvec2 pixCoord = gl_GlobalInvocationID.xy;
  if (pixCoord.x < CLIPMAP_RESOLUTION && pixCoord.y < CLIPMAP_RESOLUTION)
  {
    const vec2 worldPos = constants.toroidalUpdatePlayerWorldPos;

    const float clipmapWorldExtent = float(1 << params.level) * CLIPMAP_EXTENT_STEP;
    const float clipmapWorldSize = clipmapWorldExtent * 2.f;

    const vec2 flatUv = vec2(pixCoord) / float(CLIPMAP_RESOLUTION);
    const vec2 toroidalUvScrolloff = fract(worldPos / clipmapWorldSize) - 0.5f;

    const vec2 adjustedUv = fract(flatUv - toroidalUvScrolloff);

    const float h = imageLoad(geom[params.level], ivec2(pixCoord)).x;
    const uint hOrdUint = float_to_ordered_uint(h);

    // @SPEED may be here shader memory trick should be done first. However,
    // for that we'd need to lign up work groups to chunks.
    const ivec2 chunkCoord = ivec2(floor(adjustedUv * float(TERRAIN_CHUNKS_LEVEL_DIM)));
    if (params.level == 0)
    {
      const int chunkLinearCoord = chunkCoord.y * TERRAIN_CHUNKS_LEVEL_DIM + chunkCoord.x;
      atomicMin(chunkHeightBoundsData.firstLevel[chunkLinearCoord].minZOrdUint, hOrdUint);
      atomicMax(chunkHeightBoundsData.firstLevel[chunkLinearCoord].maxZOrdUint, hOrdUint);
    } // @NOTE: this only works for one-wide trim
    else if (
      chunkCoord.x == 0 || chunkCoord.x == TERRAIN_CHUNKS_LEVEL_DIM - 1 ||
      chunkCoord.y == 0 || chunkCoord.y == TERRAIN_CHUNKS_LEVEL_DIM - 1)
    {
      const int chunkLinearCoord =
        chunkCoord.y == 0 ? chunkCoord.x :
        chunkCoord.y == TERRAIN_CHUNKS_LEVEL_DIM - 1 ? chunkCoord.x + TERRAIN_CHUNKS_LEVEL_DIM + 2 * (TERRAIN_CHUNKS_LEVEL_DIM - 2) :
        TERRAIN_CHUNKS_LEVEL_DIM + 2 * (chunkCoord.y - 1) + (chunkCoord.x == 0 ? 1 : 0);
      atomicMin(chunkHeightBoundsData.otherLevels[params.level - 1][chunkLinearCoord].minZOrdUint, hOrdUint);
      atomicMax(chunkHeightBoundsData.otherLevels[params.level - 1][chunkLinearCoord].maxZOrdUint, hOrdUint);
    }
  }
}
