#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "defs.h"
#include "terrain.h"
#include "constants.h"
#include "draw.h"

#include "grass.comp.inc"
#include "common.frag.inc"

layout(local_size_x = BASE_WORK_GROUP_SIZE) in;

layout(binding = 8, set = 0) uniform constants_t
{
  Constants constants;
};

layout(binding = 9, set = 0) uniform view_params_t
{
  ViewParams viewParams;
};

layout(binding = 10, set = 0) readonly buffer gen_t
{
  GRASS_GEN_DATA_MEMBERS
};

layout(binding = 11, set = 0) readonly buffer template_t
{
  vec2 templateGrassPositions[];
};

layout(binding = 12, set = 0) buffer cmd_t
{
  IndirectCommand command;
};

layout(binding = 13, set = 0) writeonly buffer instances_t
{
  GrassInstance culledInstances[];
};

#include "culling.comp.inc"
#include "terrain_mesh.glsl.inc"

layout(push_constant) uniform params_t
{
  uint detailId;
} params;

float fast_quad_sine_fake(float x)
{
  x = mod(x, 2.f * SHADER_PI);
  float s = x > SHADER_PI ? -1.f : 1.f;
  x = mod(x, SHADER_PI);
  float t = x / SHADER_PI;
  return s * 4.f * t * (1.f - t);
}

float wind_oscillator(float time, vec2 worldPos)
{
  float phase = dot(worldPos, vec2(0.3, 0.7));
  float w = 0.0;
  w += 0.50 * fast_quad_sine_fake(time * 1.0000 + phase);
  w += 0.25 * fast_quad_sine_fake(time * 2.7183 + phase * 1.7);
  w += 0.10 * fast_quad_sine_fake(time * 7.3891 + phase * 2.3);
  return w;
}

vec2 random_dir_notrig(vec2 seed)
{
  const float x = basic_noise(seed);
  const float y = basic_noise(vec2(x, seed.x));
  return normalize(2.f * vec2(x, y) - 1.f);
}

vec3 calc_wind_pos_offset(
  float t, float relAmp, float strengthPeriod, vec3 grassPos, float strengthFalloff, vec2 wvn, float shrinkFactor, float strScale, float strPow)
{
  float strengthOscillation = relAmp * wind_oscillator(strengthPeriod * t, grassPos.xz);
  float strengthBase = pow(constants.windStrength * strScale, strPow);

  float windInfluenceAmt = strengthBase * (1.f + strengthOscillation) * strengthFalloff;
  vec2 windInfluence = wvn * windInfluenceAmt;
  return shrinkFactor * vec3(windInfluence.x, -0.5f * (windInfluenceAmt * windInfluenceAmt), windInfluence.y);
}

void main(void)
{
  const uint vegTypeId = terrainSource.details[params.detailId].vegetationId;
  const TerrainVegetationRule rule = terrainSource.vegetationTypes[vegTypeId];

  uint chunkId = gl_GlobalInvocationID.x / rule.templateBufferSize;
  if (chunkId >= chunkCount)
    return;

  vec2 chunkPosPlanar = chunkOrigins[chunkId];
  uint templateId = rule.templateBufferOffset + (gl_GlobalInvocationID.x - chunkId * rule.templateBufferSize);
  vec2 templatePos = templateGrassPositions[templateId];

  int oriId = basic_noise_int(chunkPosPlanar, 0, 3);
  if ((oriId & 1) != 0)
    templatePos.x = VEGETATION_CHUNK_SIZE - templatePos.x;
  if ((oriId & 2) != 0)
    templatePos.y = VEGETATION_CHUNK_SIZE - templatePos.y;

  vec2 grassPosPlanar = chunkPosPlanar + templatePos;
  vec2 grassPosPlanarRelToClipmap = grassPosPlanar - constants.toroidalUpdatePlayerWorldPos;

  vec4 matdata = load_matdata_clipmap(grassPosPlanarRelToClipmap);
  uint detailMask = floatBitsToUint(matdata.w);
  if ((detailMask & (1 << params.detailId)) == 0)
    return;
  uint otherDetailsMask = (detailMask & ~(1 << params.detailId));
  if (otherDetailsMask != 0)
  {
    uint conflictingCount = bitCount(otherDetailsMask);
    if (basic_noise_int(grassPosPlanar, 0, int(terrainSource.detailCount)) < conflictingCount)
      return;
  }

  float height = sample_geom_clipmap_exact(grassPosPlanarRelToClipmap);
  vec3 grassPos = vec3(grassPosPlanar.x, height, grassPosPlanar.y);

  float instDist = length(viewParams.viewPos - grassPos);
  if (instDist > constants.vegetationRenderingDistance)
    return;

  const mat4 instMat = translation(grassPos);
  const float r = rule.radius * 1.5f; // for wind
  const BBox bbox = {
    vec4(-r, -rule.height * GRASS_SANK_PORTION        , -r, 1.f),
    vec4( r,  rule.height * (1.f - GRASS_SANK_PORTION),  r, 1.f)};
  InstanceViewRelatedData payload;

  if (instance_is_in_view(bbox, instMat, constants.cullingMode, payload))
  {
    const float shrinkFactor = min(
      (instDist - constants.vegetationRenderingDistance) /
      (constants.vegetationRenderingDropoffDistance - constants.vegetationRenderingDistance),
      1.f);

    const vec2 rotDir = random_dir_notrig(grassPos.xz);
    const uvec2 rotDirQ = uvec2((rotDir * 0.5f + 0.5f) * 65535.f);

    const uint instId = atomicAdd(command.instanceCount, 1);
    culledInstances[instId].pos = grassPos;
    culledInstances[instId].idAndSf = (vegTypeId << GRASS_SF_BITS) | (floatBitsToUint(shrinkFactor) >> (GRASS_ID_BITS - 1));
    culledInstances[instId].windOffset = vec3(0.f);
    culledInstances[instId].prevWindOffset = vec3(0.f);
    culledInstances[instId].dirQuantized = ((rotDirQ.x & 0xFFFF) << 16) | (rotDirQ.y & 0xFFFF);

    if (constants.windStrength >= 0.001f)
    {
      vec2 wvn = constants.windDirection;
      float tAlongDir = dot(wvn, grassPos.xz);
      float dist = 5.f + fast_quad_sine_fake(130.f * tAlongDir);

      const float lambda = 0.5f;
      const float plambda = 0.5f;
      const float pscale = 5.f;
      const float relAmp = 0.4f;
      const float strScale = 0.02f;
      const float strPow = 0.3f;

      float strengthFalloff = lambda + (1.f - lambda) / (1.f + dist);
      float strengthPeriod = pscale * (plambda + (1.f - plambda) / (1.f + dist));

      culledInstances[instId].windOffset = calc_wind_pos_offset(
        constants.time, relAmp, strengthPeriod, grassPos, strengthFalloff, wvn, shrinkFactor, strScale, strPow);
      culledInstances[instId].prevWindOffset = calc_wind_pos_offset(
        constants.time - constants.dt, relAmp, strengthPeriod, grassPos, strengthFalloff, wvn, shrinkFactor, strScale, strPow);
    }
  }
}
