#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "water.h"
#include "constants.h"


layout(local_size_x = WATER_CASCADE_RES, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0, set = 0, rgba32f) uniform image2D buffers[WATER_FFT_BUFFER_COUNT];

layout(push_constant) uniform params_t
{
  uint vert;
  uint invert; // for debuge
  uint scale;
  uint permute;
} params;

shared vec4 cache[2][WATER_CASCADE_RES];

uint bitrev_index(uint id)
{
  const uint shift = 32 - WATER_CASCADE_RES_POW;
  return bitfieldReverse(id) >> shift;
}

vec2 fetch_component(vec4 pack, uint comp)
{
  return comp == 0 ? pack.xy : pack.zw;
}

vec4 comp_mult_double(vec4 a, vec4 b)
{
  return vec4(
    a.x * b.x - a.y * b.y, a.x * b.y + a.y * b.x,
    a.z * b.z - a.w * b.w, a.z * b.w + a.w * b.z);
}

vec4 comp_exp_double(float theta)
{
  const vec2 single = vec2(cos(theta), sin(theta));
  return vec4(single, single);
}

vec4 comp_conj_double(vec4 a)
{
  return vec4(a.x, -a.y, a.z, -a.w);
}

void main(void)
{
  const bool vert = params.vert != 0;
  const bool inv = params.invert != 0;
  const bool scl = params.scale != 0;
  const bool prm = params.permute != 0;

  // these all are same as global
  const uint lane = gl_WorkGroupID.y;
  const uint bufferId = gl_WorkGroupID.z;
  const uint kId = gl_LocalInvocationID.x;

  if (bufferId >= WATER_FFT_BUFFER_COUNT || lane >= WATER_CASCADE_RES || kId >= WATER_CASCADE_RES)
    return;

  // Simple radix-2 cooley-tukey fully in shared mem/one wg.
  // We do 2 lanes in one go to avoid sync issues.

  const ivec2 copyCursorBase = ivec2(lane, kId);
  const ivec2 copyCursor = vert ? copyCursorBase : copyCursorBase.yx;

  // Read all elements to cache with bit-reverse index.
  cache[0][bitrev_index(kId)] = imageLoad(buffers[bufferId], copyCursor);

  barrier();

  // Run FFT
  for (uint shift = 0; shift < WATER_CASCADE_RES_POW; ++shift)
  {
    const uint srcid = shift & 1;
    const uint dstid = ~shift & 1;

    const uint gsize = 2 << shift;
    const uint hsize = gsize / 2;
    const uint relid = kId % gsize;
    const uint basid = gsize * (kId / gsize);

    const uint lowid = basid + (relid % hsize);
    const uint uppid = lowid + hsize;

    // Conjugate cuz ifft
    const vec4 twiddleBase = comp_exp_double(-SHADER_TWO_PI * float(relid) / float(gsize));
    const vec4 twiddle = inv ? comp_conj_double(twiddleBase) : twiddleBase;
    const vec4 res = cache[srcid][lowid] + comp_mult_double(twiddle, cache[srcid][uppid]);

    cache[dstid][kId] = res;

    barrier();
  }

  // Store calculations back. No bit reversion needed.
  vec4 result = cache[WATER_CASCADE_RES_POW & 1][kId];
  if (prm)
    result *= ((lane + kId) % 2 == 0 ? 1.f : -1.f);
  if (scl)
    result = result / float(WATER_CASCADE_RES) / float(WATER_CASCADE_RES);
  imageStore(buffers[bufferId], copyCursor, result);
}
