#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "water.h"
#include "constants.h"

layout(local_size_x = WATER_WORKGROUP_DIM, local_size_y = WATER_WORKGROUP_DIM, local_size_z = 1) in;

layout(binding = 0, set = 0) buffer caustics_t
{
  uint accum[];
};

layout(binding = 1, set = 0) uniform sampler2D displacement[WATER_CASCADE_COUNT];
layout(binding = 2, set = 0) uniform sampler2D derivatives[WATER_CASCADE_COUNT];
layout(binding = 3, set = 0) uniform sampler2D turbulence[WATER_CASCADE_COUNT];

void main(void)
{
  ivec2 imCoord = ivec2(gl_GlobalInvocationID.xy);

  if (imCoord.x >= WATER_CAUSTIC_MAP_RES || imCoord.y >= WATER_CAUSTIC_MAP_RES)
    return;
  
  // @TEST
  uint add = ((imCoord.x + imCoord.y) % 2 == 1) ? 100 : 0;
  imCoord = imCoord / 2 * 2;
  atomicAdd(accum[imCoord.x + WATER_CAUSTIC_MAP_RES * imCoord.y], add);
}
