
#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "water.h"
#include "constants.h"

layout(local_size_x = WATER_WORKGROUP_DIM, local_size_y = WATER_WORKGROUP_DIM, local_size_z = 1) in;

layout(binding = 0, set = 0) writeonly buffer caustics_t
{
  uint accum[];
};

void main(void)
{
  const ivec2 imCoord = ivec2(gl_GlobalInvocationID.xy);
  
  if (imCoord.x >= WATER_CAUSTIC_MAP_RES || imCoord.y >= WATER_CAUSTIC_MAP_RES)
    return;
  
  accum[imCoord.x + WATER_CAUSTIC_MAP_RES * imCoord.y] = 0;
}
