#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "water.h"
#include "constants.h"

layout(local_size_x = WATER_WORKGROUP_DIM, local_size_y = WATER_WORKGROUP_DIM, local_size_z = 1) in;

layout(binding = 0, set = 0, rgba32f) uniform image2D spectraTex[WATER_CASCADE_COUNT];

void main(void)
{
  const int cascade = int(gl_GlobalInvocationID.z);
  if (cascade >= WATER_CASCADE_COUNT)
    return;

  const ivec2 imSz    = imageSize(spectraTex[cascade]);
  const ivec2 imCoord = ivec2(gl_GlobalInvocationID.xy);
  const vec2 imUv     = vec2(imCoord) / vec2(imSz);
  
  if (imCoord.x >= imSz.x || imCoord.y >= imSz.y)
    return;

  vec2 h0 = imageLoad(spectraTex[cascade], imCoord).xy;
  vec2 h0minusK = imageLoad(spectraTex[cascade], (imSz - imCoord) % imSz).xy;

  imageStore(spectraTex[cascade], imCoord, vec4(h0.x, h0.y, h0minusK.x, -h0minusK.y));
}


