#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "water.h"
#include "constants.h"

layout(local_size_x = WATER_WORKGROUP_DIM, local_size_y = WATER_WORKGROUP_DIM, local_size_z = 1) in;

layout(binding = 0, set = 0, rgba32f) uniform writeonly image2D wkTex[WATER_CASCADE_COUNT];
layout(binding = 1, set = 0, rgba32f) uniform writeonly image2D spectraTex[WATER_CASCADE_COUNT];

layout(binding = 6, set = 0) uniform water_source_t
{
  WaterSourceData source;
};
layout(binding = 8, set = 0) uniform constants_t
{
  Constants constants;
};

float sech(float v)
{
  return 1.f / cosh(v);
}

#include "bindless.glsl.inc"

vec2 get_blue_noise(vec2 uv)
{
  return sample_bindless_tex_lod(constants.blueNoiseTexSmp, uv, 0.f).xy;
}

void main(void)
{
  const int cascade = int(gl_GlobalInvocationID.z);
  if (cascade >= WATER_CASCADE_COUNT)
    return;

  const ivec2 imSz    = imageSize(wkTex[cascade]);
  const ivec2 imCoord = ivec2(gl_GlobalInvocationID.xy);
  const vec2 imUv     = vec2(imCoord) / vec2(imSz);
  
  if (imCoord.x >= imSz.x || imCoord.y >= imSz.y)
    return;

  float l = 0.f;
  switch (cascade)
  {
  case 0:  l = source.l0; break;
  case 1:  l = source.l1; break;
  case 2:  l = source.l2; break;
  default:                break;
  }

  // Phillips
  const float L = 1000.f;
  const float A = 1.f;
  const float g = 9.81f;

  ivec2 offId = imCoord - (imSz / 2);
  float dk = SHADER_TWO_PI / l;
  vec2 k = dk * vec2(offId);
  float wavenumber = length(k);

  float omega = sqrt(g * wavenumber);

  float ph = A * exp(-1.f / wavenumber / wavenumber / L / L) / wavenumber / wavenumber / wavenumber / wavenumber;
  float cosine = dot(normalize(k), normalize(constants.windDirection));
  float phDir = ph * cosine * cosine * cosine * cosine * cosine * cosine;

  vec2 initialSpectrum = sqrt(0.5f) * get_blue_noise(imUv) * sqrt(phDir);

  // @TODO: ensure no overlap with other cascades
  float minWavenumberCascade = 0.0001f;
  float maxWavenumberCascade = 9999.f;

  if (wavenumber < minWavenumberCascade || wavenumber > maxWavenumberCascade)
  {
    imageStore(wkTex[cascade], imCoord, vec4(k.x, 1.f, k.y, 0.f));
    imageStore(spectraTex[cascade], imCoord, vec4(0.f));
  }
  else
  {
    imageStore(wkTex[cascade], imCoord, vec4(k.x, 1.f / wavenumber, k.y, omega));
    imageStore(spectraTex[cascade], imCoord, vec4(initialSpectrum, 0.f, 0.f));
  }
}

