#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "draw.h"
#include "geometry.h"
#include "constants.h"


layout(local_size_x = BASE_WORK_GROUP_SIZE) in;

#include "instancing.glsl.inc"
#include "culling.comp.inc"

layout(binding = 3, set = 0) writeonly buffer instances_t
{
  DrawableInstance markedInstances[];
};
layout(binding = 4, set = 0) buffer commands_t
{
  IndirectCommand commands[];
};

void main(void)
{
  const uint idx = gl_GlobalInvocationID.x;
  if (idx < allInstances.length())
  {
    const CullableInstance inst = allInstances[idx];

    const mat4 instMat = get_inst_matrix(inst);
    const BBox bbox = get_inst_bbox(inst);
    InstanceViewRelatedData payload;

    if (instance_is_in_view(bbox, instMat, constants.cullingMode, payload))
    {
      const uint destId =
        commands[inst.commandId].firstInstance +
        atomicAdd(commands[inst.commandId].instanceCount, 1);

      markedInstances[destId].instId = inst.instId;
      markedInstances[destId].materialId = inst.materialId;
      markedInstances[destId].commandId = inst.commandId;
      markedInstances[destId].flags = inst.flags;
      markedInstances[destId].minViewZ = payload.minZ;
      markedInstances[destId].maxViewZ = payload.maxZ;
    }
  }
}
