#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "draw.h"
#include "geometry.h"

layout(local_size_x = BASE_WORK_GROUP_SIZE) in;

layout(binding = 0, set = 0) writeonly buffer commands_t
{
  IndirectCommand commands[];
};
layout(binding = 1, set = 0) buffer data_t
{
  ViewData vdata;
};

void main(void)
{
  uint idx = gl_GlobalInvocationID.x;
  if (idx == 0)
  {
    vdata.prevMinViewZOrderedUint = vdata.minViewZOrderedUint;
    vdata.prevMaxViewZOrderedUint = vdata.maxViewZOrderedUint;
    vdata.minViewZOrderedUint = SHADER_UINT_MAX;
    vdata.maxViewZOrderedUint = 0;
  }
  if (idx < commands.length())
    commands[idx].instanceCount = 0;
}
