#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "cpp_glsl_compat.h"
#include "draw.h"

// @NOTE: uints so as to have atomic ops work
struct BufferMinMax
{
  uint bmin;
  uint bmax;
};

// @TODO: do not take minmaxz on instances that were culled out!

#define TYPE DrawableInstance
#define RTYPE BufferMinMax
#define INIT                                                                                       \
  BufferMinMax(float_to_ordered_uint(SHADER_FLT_MAX), float_to_ordered_uint(-SHADER_FLT_MAX))

#define ADD_OP(mm_, d_)                                                                            \
  BufferMinMax(                                                                                    \
    min((mm_).bmin, float_to_ordered_uint((d_).minViewZ)),                                         \
    max((mm_).bmax, float_to_ordered_uint((d_).maxViewZ)))
#define MERGE_OP(mm1_, mm2_)                                                                       \
  BufferMinMax(min((mm1_).bmin, (mm2_).bmin), max((mm1_).bmax, (mm2_).bmax))
#define ATOMIC_OP(to_, from_)                                                                      \
  do                                                                                               \
  {                                                                                                \
    atomicMin(to_.bmin, (from_).bmin);                                                             \
    atomicMax(to_.bmax, (from_).bmax);                                                             \
  } while (false)

#define VALID(r_) ((r_).bmin <= (r_).bmax)

#include "buffer_aci_statistic.comp.inc"
