#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require


#include "draw.h"

layout(local_size_x = BASE_WORK_GROUP_SIZE) in;

layout(binding = 0, set = 0) writeonly buffer commands_t
{
  IndirectCommand commands[];
};

void main(void)
{
  uint idx = gl_GlobalInvocationID.x;
  if (idx < commands.length())
    commands[idx].instanceCount = 0;
}
